//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientsRegistration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public DateTime CreatedAt { get; set; }

        public override bool Equals(object obj)
        {
            var item = obj as Client;

            if (item == null)
            {
                return false;
            }

            return this.Name.Equals(item.Name) && this.Email.Equals(item.Email);
        }

        public override int GetHashCode()
        {
            return this.Name.GetHashCode() + this.Email.GetHashCode();
        }
    }
}
